//CRIAR UMA FUNÇÃO QUE RECEBE UM PARAMETRO 
//GRAVAR EM UM ARQUIVO CHAMADO LOG.TXT
//SE O ARQUIVO NÃO EXISTE , DEVE-SE CRIAR O LOG.TXT;
//SE O ARQUIVO EXISTE, DEVE-SE ADICIONAR O CONTEÚDO ENVIADO EM UMA NOVA LINHA
//ADICIONAR NO LOG A DATA E HORA QUE FOI GRAVADO

//DATA -> CONTEÚDO

const funcaoImprimirLog = require("./Desafio03_modulo");

funcaoImprimirLog('Primeiro Log')



